# Generated by Django 5.2.12 on 2026-03-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="stock_distributions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Split of quantity between press and home stock, e.g. [{"stock_type": "press_stock", "quantity": 25}, {"stock_type": "home_stock", "quantity": 25}]',
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="stock_type",
            field=models.CharField(
                choices=[("press_stock", "Press Stock"), ("home_stock", "Home Stock")],
                default="press_stock",
                help_text="Which stock to add to (used when stock_distributions is empty)",
                max_length=20,
            ),
        ),
    ]
