# Generated by Django 4.2.7 on 2026-04-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_supplier_previous_balance_reference'),
        ('purchases', '0005_purchase_updated_at'),
    ]

    operations = [
    ]
