# Generated by Django 4.2.7 on 2026-03-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_item_flag_design_type"),
        ("customers", "0002_customer_previous_balance"),
        ("orders", "0003_order_customer_name_orderitem_item_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="item_name",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="inventory.item",
            ),
        ),
    ]
