# Generated by Django 4.2.7 on 2026-03-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderitem_delivered_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In_Production", "In Production"),
                    ("Ready", "Ready"),
                    ("Partially_Delivered", "Partially Delivered"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
    ]
