# Generated by Django 6.0.3 on 2026-04-02 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_unit_price'),
        ('orders', '0007_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='manual_item_name',
            field=models.CharField(blank=True, help_text='Item name for manual entries', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.item'),
        ),
    ]
