# Generated by Django 4.2.7 on 2026-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_manual_serial_quotation_purchase_cost_orderitem_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_estimate',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit (customer)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='purchase_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at order time (internal)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='price_estimate',
            field=models.DecimalField(decimal_places=2, help_text='Quoted sale price per unit (customer-facing)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='purchase_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Internal purchase/cost per unit', max_digits=10),
        ),
    ]
