# Generated by Django 4.2.7 on 2026-05-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_price_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='manual_serial_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Manual quotation / ledger serial number', max_length=100),
        ),
    ]
