"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from typing import List

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(key: str, default: bool = False) -> bool:
    val = os.environ.get(key)
    if val is None:
        return default
    return val.strip().lower() in ('1', 'true', 'yes', 'on')


def _split_csv(key: str, default: str = '') -> List[str]:
    raw = os.environ.get(key, default).strip()
    if not raw:
        return []
    return [x.strip() for x in raw.split(',') if x.strip()]


# --- Local vs production (nothing is "commented out" — behavior follows DEBUG) ---
# Local:  Do not set DJANGO_DEBUG, or set DJANGO_DEBUG=True  → DEBUG=True, ALLOWED_HOSTS=['*'],
#         CORS/CSRF include localhost (React npm start on :3000, etc.).
# Server: Set DJANGO_DEBUG=False and DJANGO_SECRET_KEY in the environment → production defaults
#         for afghanflags.com (see backend/.env.example). Override hosts/CORS with DJANGO_* vars.

# Quick-start development settings — load production values from environment (see backend/.env.example)
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-^+meok6l)&fa$j#!ijv^tl178!o10al1$69kge*wpeu89qpg%@',
)

DEBUG = _env_bool('DJANGO_DEBUG', True)

_allowed = _split_csv('DJANGO_ALLOWED_HOSTS')
if _allowed:
    ALLOWED_HOSTS = _allowed
elif DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['afghanflags.com', 'www.afghanflags.com', 'api.afghanflags.com']

# CORS: local dev origins + optional DJANGO_CORS_ALLOWED_ORIGINS (e.g. https://afghanflags.com)
_CORS_DEV = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:3002',
    'http://localhost:5500',
    'http://127.0.0.1:5500',
    'http://127.0.0.1:3000',
]
_CORS_PROD_DEFAULT = [
    'https://afghanflags.com',
    'https://www.afghanflags.com',
    'https://api.afghanflags.com',
]
_cors_extra = _split_csv('DJANGO_CORS_ALLOWED_ORIGINS')
if DEBUG:
    CORS_ALLOWED_ORIGINS = _CORS_DEV + _cors_extra
else:
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys(_CORS_PROD_DEFAULT + _cors_extra))

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_PREFLIGHT_MAX_AGE = 86400


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'core',
    'inventory',
    'customers',
    'orders',
    'sales',
    'purchases',
    'employees',
    'expenses',
    'dashboard',
    'reports',
    'roznamcha',
    'rent',
    'printing',
    'bank',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.NoCacheApiMiddleware',
    'core.middleware.AuditLogMiddleware',
]

_CSRF_DEV = [
    'http://localhost:3000',
    'http://localhost:3002',
    'http://localhost:5500',
    'http://127.0.0.1:5500',
    'http://127.0.0.1:3000',
]
_CSRF_PROD_DEFAULT = [
    'https://afghanflags.com',
    'https://www.afghanflags.com',
    'https://api.afghanflags.com',
]
_csrf_extra = _split_csv('DJANGO_CSRF_TRUSTED_ORIGINS')
if DEBUG:
    CSRF_TRUSTED_ORIGINS = _CSRF_DEV + _csrf_extra
else:
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(_CSRF_PROD_DEFAULT + _csrf_extra))

CSRF_EXEMPT_VIEWS = ['expenses']
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False

# HTTPS (set DJANGO_BEHIND_PROXY=1 when nginx terminates SSL)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    if _env_bool('DJANGO_SECURE_SSL_REDIRECT', True):
        SECURE_SSL_REDIRECT = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kabul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
