# Generated by Django 4.2.7 on 2026-04-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_shop_owner_name'),
        ('rent', '0002_shop_tenant_phone'),
    ]

    operations = [
    ]
