# Generated by Django 4.2.7 on 2026-02-13 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")
                        ],
                    ),
                ),
                ("address", models.TextField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "registration_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "ordering": ["-registration_date"],
                "indexes": [
                    models.Index(
                        fields=["name", "phone"], name="customers_c_name_ae0c34_idx"
                    )
                ],
            },
        ),
    ]
