# Generated by Django 4.2.7 on 2026-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="previous_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Balance before system implementation",
                max_digits=12,
            ),
        ),
    ]
