# Generated by Django 4.2.7 on 2026-03-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_previous_balance"),
        ("customers", "0002_customerbalancepayment"),
    ]

    operations = []
