# Generated by Django 4.2.7 on 2026-04-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_previous_balance_reference'),
        ('customers', '0003_merge_20260312_1544'),
    ]

    operations = [
    ]
