# Generated by Django 6.0.3 on 2026-04-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('income', 'Income')], db_index=True, default='manual', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'bank_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
