# Generated by Django 4.2.7 on 2026-02-13 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FlagDesignType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Flag Design Type",
                "verbose_name_plural": "Flag Design Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("raw_material", "Raw Material"),
                            ("finished_product", "Finished Product"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "press_stock",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="Stock for press operations"
                    ),
                ),
                (
                    "home_stock",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Stock for home sales (controlled by home admin)",
                    ),
                ),
                (
                    "current_stock",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        editable=False,
                        help_text="Total stock (press_stock + home_stock)",
                    ),
                ),
                ("minimum_stock", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.category",
                    ),
                ),
                (
                    "flag_design_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Design type (e.g., Satan, Parashut)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.flagdesigntype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "Stock In"), ("OUT", "Stock Out")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "stock_type",
                    models.CharField(
                        choices=[
                            ("press_stock", "Press Stock"),
                            ("home_stock", "Home Stock"),
                            ("both", "Both Stocks"),
                        ],
                        default="press_stock",
                        help_text="Which stock to affect",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SALE", "Sale"),
                            ("SALE_CANCEL", "Sale Cancellation"),
                            ("ORDER", "Order"),
                            ("ORDER_CANCEL", "Order Cancellation"),
                            ("PURCHASE", "Purchase"),
                            ("PRODUCTION", "Production"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                        ],
                        db_index=True,
                        help_text="Type of transaction reference",
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the related sale, order, or purchase",
                        null=True,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "transaction_type"],
                        name="inventory_s_item_id_8a1965_idx",
                    ),
                    models.Index(
                        fields=["created_at", "transaction_type"],
                        name="inventory_s_created_3e21a2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_stock", models.PositiveIntegerField()),
                ("minimum_stock", models.PositiveIntegerField()),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_resolved", "created_at"],
                        name="inventory_l_is_reso_3a1653_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["item_type", "current_stock"],
                name="inventory_i_item_ty_ba201a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category", "item_type"], name="inventory_i_categor_0d40ae_idx"
            ),
        ),
    ]
