# Generated by Django 4.2.7 on 2026-02-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_add_dynamic_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="flag_design_type",
            field=models.ForeignKey(
                blank=True,
                help_text="For Flag category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.flagdesigntype",
            ),
        ),
    ]
