# Generated by Django 4.2.7 on 2026-05-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit', max_digits=10, null=True),
        ),
    ]
