# Generated by Django 4.2.7 on 2026-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_printingjobitem_making_selling_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingjobitem',
            name='selling_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling price per unit (AFN); subtotal = qty × selling when set', max_digits=12),
        ),
    ]
