# Generated by Django 4.2.7 on 2026-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_alter_printingjobitem_selling_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingjobitem',
            name='selling_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling price per unit (AFN); profit uses qty × (selling − making); line_total uses qty × making', max_digits=12),
        ),
    ]
