# Generated by Django 4.2.7 on 2026-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_sale_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="flag_stand_size",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
