# Generated by Django 4.2.7 on 2026-03-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_item_flag_design_type"),
        ("customers", "0002_customer_previous_balance"),
        ("sales", "0003_saleitem_flag_stand_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="Manual customer name if not from customer list",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="item_name",
            field=models.CharField(
                blank=True,
                help_text="Manual item name if not from inventory",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_items",
                to="inventory.item",
            ),
        ),
    ]
