# Generated by Django 4.2.7 on 2026-03-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_item_flag_design_type"),
        ("customers", "0002_customer_previous_balance"),
        ("sales", "0004_sale_customer_name_saleitem_item_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Customer name if not in system", max_length=255
                    ),
                ),
                ("sale_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost of items purchased",
                        max_digits=12,
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net profit (net_amount - cost_amount)",
                        max_digits=12,
                    ),
                ),
                (
                    "due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Unpaid", "Unpaid"),
                            ("Partial", "Partial"),
                            ("Paid", "Paid"),
                        ],
                        db_index=True,
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_sales",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "direct_sales",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.RemoveField(
            model_name="sale",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="item_name",
        ),
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_items",
                to="inventory.item",
            ),
        ),
        migrations.CreateModel(
            name="DirectSalePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("check", "Check"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "direct_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sales.directsale",
                    ),
                ),
            ],
            options={
                "db_table": "direct_sale_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="DirectSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(help_text="Item description", max_length=255),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selling price per unit",
                        max_digits=10,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Purchase cost per unit",
                        max_digits=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "cost_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        help_text="Where item was purchased from",
                        max_length=255,
                    ),
                ),
                (
                    "direct_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.directsale",
                    ),
                ),
            ],
            options={
                "db_table": "direct_sale_items",
            },
        ),
    ]
