# Generated by Django 5.2.12 on 2026-03-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_directsale_remove_sale_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directsale",
            name="customer_name",
            field=models.CharField(
                default="", help_text="Customer name if not in system", max_length=255
            ),
        ),
    ]
