# Generated by Django 4.2.7 on 2026-04-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_sale_date_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': [models.OrderBy(models.F('sale_date'), descending=True, nulls_last=True), '-id']},
        ),
    ]
