# Generated by Django 4.2.7 on 2026-02-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expense_date", models.DateField(db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("office", "Office Supplies"),
                            ("utilities", "Utilities"),
                            ("transport", "Transportation"),
                            ("marketing", "Marketing"),
                            ("maintenance", "Maintenance"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-expense_date"],
            },
        ),
    ]
