# Generated by Django 4.2.7 on 2026-02-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("father_name", models.CharField(max_length=200)),
                ("nid", models.CharField(db_index=True, max_length=20, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("join_date", models.DateField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("loan_date", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Interest rate in percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "repayment_plan",
                    models.TextField(
                        blank=True, help_text="Plan for repaying the loan"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Paid", "Paid"),
                            ("Partial", "Partial"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-loan_date"],
            },
        ),
        migrations.CreateModel(
            name="Advance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_given", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "return_plan",
                    models.TextField(
                        blank=True, help_text="Plan for returning the advance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Returned", "Returned")],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("is_deducted", models.BooleanField(db_index=True, default=False)),
                ("deduction_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advances",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_given"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(db_index=True)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "advance_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
                "unique_together": {("employee", "month")},
            },
        ),
    ]
