# Generated by Django 4.2.7 on 2026-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_salarypayment_period_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarypayment",
            name="month",
            field=models.DateField(
                db_index=True,
                help_text="Month or week start date for the salary period",
            ),
        ),
    ]
