# Generated by Django 4.2.7 on 2026-02-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RozNamcha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(db_index=True, max_length=200)),
                ("date", models.DateField(db_index=True)),
                ("description", models.TextField(blank=True)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Roz Namcha",
                "verbose_name_plural": "Roz Namcha",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["date", "item_name"], name="roznamcha_r_date_83ec84_idx"
                    )
                ],
            },
        ),
    ]
