# Generated by Django 4.2.7 on 2026-02-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roznamcha", "0002_roznamcha_transaction_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="roznamcha",
            new_name="roznamcha_r_transac_0de352_idx",
            old_name="roznamcha_r_transac_idx",
        ),
    ]
