# Generated by Django 4.2.7 on 2026-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of module permissions for staff users",
            ),
        ),
    ]
